version: '3.8'

services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    env_file:
      - ./api-server/.env

  s3-reverse-proxy:
    build:
      context: ./s3-reverse-proxy
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./s3-reverse-proxy/.env
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cloudflare:/etc/nginx/cloudflare
    ports:
      - '80:80'
    depends_on:
      - api-server
      - s3-reverse-proxy
